api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 200
        pagination_client_items_per_page: true
        pagination_client_enabled: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    openapi:
        swagger_ui_extra_configuration:
            persistAuthorization: false
