<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__PasswordResetToken__CLASSMETADATA__' => 0,
'App__Entity__Stock__CLASSMETADATA__' => 1,
'App__Entity__User__CLASSMETADATA__' => 2,
'App__Entity__Watchlist__CLASSMETADATA__' => 3,
'App__Entity__WatchlistItem__CLASSMETADATA__' => 4,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PasswordResetToken',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'tokenHash' => $o[2],
                    'expiresAt' => $o[3],
                    'usedAt' => $o[4],
                    'createdAt' => $o[5],
                    'ipAddress' => $o[6],
                    'userAgent' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'token_hash' => 'tokenHash',
                    'expires_at' => 'expiresAt',
                    'used_at' => 'usedAt',
                    'created_at' => 'createdAt',
                    'ip_address' => 'ipAddress',
                    'user_agent' => 'userAgent',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'tokenHash' => 'token_hash',
                    'expiresAt' => 'expires_at',
                    'usedAt' => 'used_at',
                    'createdAt' => 'created_at',
                    'ipAddress' => 'ip_address',
                    'userAgent' => 'user_agent',
                ],
            ],
            'table' => [
                [
                    'name' => 'password_reset_token',
                    'indexes' => [
                        [
                            'columns' => [
                                'token_hash',
                            ],
                        ],
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\PasswordResetToken',
                9 => 'user_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'datetime_immutable',
                'datetime_immutable',
                'datetime_immutable',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'tokenHash',
                'expiresAt',
                'usedAt',
                'createdAt',
                'ipAddress',
                'userAgent',
            ],
            'columnName' => [
                1 => 'id',
                'token_hash',
                'expires_at',
                'used_at',
                'created_at',
                'ip_address',
                'user_agent',
            ],
            'length' => [
                2 => 255,
                6 => 64,
                255,
            ],
            'nullable' => [
                4 => true,
                6 => true,
                true,
                9 => false,
            ],
            'fetch' => [
                8 => 2,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\PasswordResetToken',
            ],
            'sourceToTargetKeyColumns' => [
                8 => [
                    'user_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                8 => [
                    'id' => 'user_id',
                ],
            ],
            'joinColumns' => [
                8 => [
                    $o[9],
                ],
            ],
            'joinColumnFieldNames' => [
                8 => [
                    'user_id' => 'user_id',
                ],
            ],
            'deferrable' => [
                9 => false,
            ],
            'unique' => [
                9 => false,
            ],
            'onDelete' => [
                9 => 'CASCADE',
            ],
            'referencedColumnName' => [
                9 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'user',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\User',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Stock',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'symbol' => $o[2],
                    'exchangeCode' => $o[3],
                    'mic' => $o[4],
                    'isin' => $o[5],
                    'name' => $o[6],
                    'type' => $o[7],
                    'currency' => $o[8],
                    'country' => $o[9],
                    'sector' => $o[10],
                    'industry' => $o[11],
                    'website' => $o[12],
                    'description' => $o[13],
                    'logoUrl' => $o[14],
                    'lastPrice' => $o[15],
                    'open' => $o[16],
                    'high' => $o[17],
                    'low' => $o[18],
                    'prevClose' => $o[19],
                    'change' => $o[20],
                    'changePercent' => $o[21],
                    'avgVolume30d' => $o[22],
                    'marketCap' => $o[23],
                    'sharesOutstanding' => $o[24],
                    'floatShares' => $o[25],
                    'quoteTimestamp' => $o[26],
                    'lastUpdatedAt' => $o[27],
                    'beta' => $o[28],
                    'dividendYield' => $o[29],
                    'dividendRate' => $o[30],
                    'peTtm' => $o[31],
                    'pb' => $o[32],
                    'psTtm' => $o[33],
                    'evEbitda' => $o[34],
                    'week52High' => $o[35],
                    'week52Low' => $o[36],
                    'active' => $o[37],
                    'dataSource' => $o[38],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'symbol' => 'symbol',
                    'exchange_code' => 'exchangeCode',
                    'mic' => 'mic',
                    'isin' => 'isin',
                    'name' => 'name',
                    'type' => 'type',
                    'currency' => 'currency',
                    'country' => 'country',
                    'sector' => 'sector',
                    'industry' => 'industry',
                    'website' => 'website',
                    'description' => 'description',
                    'logo_url' => 'logoUrl',
                    'last_price' => 'lastPrice',
                    'open' => 'open',
                    'high' => 'high',
                    'low' => 'low',
                    'prev_close' => 'prevClose',
                    'change' => 'change',
                    'change_percent' => 'changePercent',
                    'avg_volume30d' => 'avgVolume30d',
                    'market_cap' => 'marketCap',
                    'shares_outstanding' => 'sharesOutstanding',
                    'float_shares' => 'floatShares',
                    'quote_timestamp' => 'quoteTimestamp',
                    'last_updated_at' => 'lastUpdatedAt',
                    'beta' => 'beta',
                    'dividend_yield' => 'dividendYield',
                    'dividend_rate' => 'dividendRate',
                    'pe_ttm' => 'peTtm',
                    'pb' => 'pb',
                    'ps_ttm' => 'psTtm',
                    'ev_ebitda' => 'evEbitda',
                    'week52_high' => 'week52High',
                    'week52_low' => 'week52Low',
                    'active' => 'active',
                    'data_source' => 'dataSource',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'symbol' => 'symbol',
                    'exchangeCode' => 'exchange_code',
                    'mic' => 'mic',
                    'isin' => 'isin',
                    'name' => 'name',
                    'type' => 'type',
                    'currency' => 'currency',
                    'country' => 'country',
                    'sector' => 'sector',
                    'industry' => 'industry',
                    'website' => 'website',
                    'description' => 'description',
                    'logoUrl' => 'logo_url',
                    'lastPrice' => 'last_price',
                    'open' => 'open',
                    'high' => 'high',
                    'low' => 'low',
                    'prevClose' => 'prev_close',
                    'change' => 'change',
                    'changePercent' => 'change_percent',
                    'avgVolume30d' => 'avg_volume30d',
                    'marketCap' => 'market_cap',
                    'sharesOutstanding' => 'shares_outstanding',
                    'floatShares' => 'float_shares',
                    'quoteTimestamp' => 'quote_timestamp',
                    'lastUpdatedAt' => 'last_updated_at',
                    'beta' => 'beta',
                    'dividendYield' => 'dividend_yield',
                    'dividendRate' => 'dividend_rate',
                    'peTtm' => 'pe_ttm',
                    'pb' => 'pb',
                    'psTtm' => 'ps_ttm',
                    'evEbitda' => 'ev_ebitda',
                    'week52High' => 'week52_high',
                    'week52Low' => 'week52_low',
                    'active' => 'active',
                    'dataSource' => 'data_source',
                ],
            ],
            'table' => [
                [
                    'name' => 'stock',
                ],
            ],
            'associationMappings' => [
                [
                    'watchlistItems' => $o[39],
                ],
            ],
            'idGenerator' => [
                $o[40],
            ],
            'name' => [
                'App\\Entity\\Stock',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'text',
                'string',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'datetime_immutable',
                'datetime_immutable',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'float',
                'boolean',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'symbol',
                'exchangeCode',
                'mic',
                'isin',
                'name',
                'type',
                'currency',
                'country',
                'sector',
                'industry',
                'website',
                'description',
                'logoUrl',
                'lastPrice',
                'open',
                'high',
                'low',
                'prevClose',
                'change',
                'changePercent',
                'avgVolume30d',
                'marketCap',
                'sharesOutstanding',
                'floatShares',
                'quoteTimestamp',
                'lastUpdatedAt',
                'beta',
                'dividendYield',
                'dividendRate',
                'peTtm',
                'pb',
                'psTtm',
                'evEbitda',
                'week52High',
                'week52Low',
                'active',
                'dataSource',
            ],
            'columnName' => [
                1 => 'id',
                'symbol',
                'exchange_code',
                'mic',
                'isin',
                'name',
                'type',
                'currency',
                'country',
                'sector',
                'industry',
                'website',
                'description',
                'logo_url',
                'last_price',
                'open',
                'high',
                'low',
                'prev_close',
                'change',
                'change_percent',
                'avg_volume30d',
                'market_cap',
                'shares_outstanding',
                'float_shares',
                'quote_timestamp',
                'last_updated_at',
                'beta',
                'dividend_yield',
                'dividend_rate',
                'pe_ttm',
                'pb',
                'ps_ttm',
                'ev_ebitda',
                'week52_high',
                'week52_low',
                'active',
                'data_source',
            ],
            'length' => [
                2 => 32,
                16,
                16,
                32,
                255,
                64,
                8,
                64,
                128,
                128,
                255,
                14 => 512,
                38 => 64,
            ],
            'nullable' => [
                3 => true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                38 => true,
            ],
            'cascade' => [
                39 => [
                    'remove',
                ],
            ],
            'fetch' => [
                39 => 2,
            ],
            'orphanRemoval' => [
                39 => true,
            ],
            'sourceEntity' => [
                39 => 'App\\Entity\\Stock',
            ],
            'mappedBy' => [
                39 => 'stock',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                39 => 'watchlistItems',
            ],
            'targetEntity' => [
                39 => 'App\\Entity\\WatchlistItem',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'firstName' => $o[2],
                    'lastName' => $o[3],
                    'email' => $o[4],
                    'passwordHash' => $o[5],
                    'avatarUrl' => $o[6],
                    'createdAt' => $o[7],
                    'updatedAt' => $o[8],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'first_name' => 'firstName',
                    'last_name' => 'lastName',
                    'email' => 'email',
                    'password_hash' => 'passwordHash',
                    'avatar_url' => 'avatarUrl',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'firstName' => 'first_name',
                    'lastName' => 'last_name',
                    'email' => 'email',
                    'passwordHash' => 'password_hash',
                    'avatarUrl' => 'avatar_url',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'app_user',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'watchlists' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'firstName',
                'lastName',
                'email',
                'passwordHash',
                'avatarUrl',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'first_name',
                'last_name',
                'email',
                'password_hash',
                'avatar_url',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 120,
                120,
                180,
                255,
                255,
            ],
            'nullable' => [
                2 => true,
                true,
                6 => true,
            ],
            'unique' => [
                4 => true,
            ],
            'cascade' => [
                9 => [
                    'persist',
                    'remove',
                ],
            ],
            'fetch' => [
                9 => 2,
            ],
            'orphanRemoval' => [
                9 => true,
            ],
            'sourceEntity' => [
                9 => 'App\\Entity\\User',
            ],
            'mappedBy' => [
                9 => 'user',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                9 => 'watchlists',
            ],
            'targetEntity' => [
                9 => 'App\\Entity\\Watchlist',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Watchlist',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'description' => $o[3],
                    'isDefault' => $o[4],
                    'createdAt' => $o[5],
                    'updatedAt' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'is_default' => 'isDefault',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'isDefault' => 'is_default',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'watchlist',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[7],
                    'items' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Watchlist',
                8 => 'user_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'boolean',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'name',
                'description',
                'isDefault',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'name',
                'description',
                'is_default',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 160,
            ],
            'nullable' => [
                3 => true,
                8 => false,
            ],
            'fetch' => [
                7 => 2,
                9 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Watchlist',
                9 => 'App\\Entity\\Watchlist',
            ],
            'inversedBy' => [
                7 => 'watchlists',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'user_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'user_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'user_id' => 'user_id',
                ],
            ],
            'deferrable' => [
                8 => false,
            ],
            'unique' => [
                8 => false,
            ],
            'onDelete' => [
                8 => 'CASCADE',
            ],
            'referencedColumnName' => [
                8 => 'id',
            ],
            'cascade' => [
                9 => [
                    'persist',
                    'remove',
                ],
            ],
            'orphanRemoval' => [
                9 => true,
            ],
            'mappedBy' => [
                9 => 'watchlist',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'user',
                9 => 'items',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\User',
                9 => 'App\\Entity\\WatchlistItem',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\WatchlistItem',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'addedAt' => $o[2],
                    'position' => $o[3],
                    'note' => $o[4],
                    'tags' => $o[5],
                    'alertPriceAbove' => $o[6],
                    'alertPriceBelow' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'added_at' => 'addedAt',
                    'position' => 'position',
                    'note' => 'note',
                    'tags' => 'tags',
                    'alert_price_above' => 'alertPriceAbove',
                    'alert_price_below' => 'alertPriceBelow',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'addedAt' => 'added_at',
                    'position' => 'position',
                    'note' => 'note',
                    'tags' => 'tags',
                    'alertPriceAbove' => 'alert_price_above',
                    'alertPriceBelow' => 'alert_price_below',
                ],
            ],
            'table' => [
                [
                    'name' => 'watchlist_item',
                ],
            ],
            'associationMappings' => [
                [
                    'watchlist' => $o[8],
                    'stock' => $o[10],
                ],
            ],
            'idGenerator' => [
                $o[12],
            ],
            'name' => [
                'App\\Entity\\WatchlistItem',
                9 => 'watchlist_id',
                11 => 'stock_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime_immutable',
                'integer',
                'text',
                'json',
                'decimal',
                'decimal',
            ],
            'fieldName' => [
                1 => 'id',
                'addedAt',
                'position',
                'note',
                'tags',
                'alertPriceAbove',
                'alertPriceBelow',
            ],
            'columnName' => [
                1 => 'id',
                'added_at',
                'position',
                'note',
                'tags',
                'alert_price_above',
                'alert_price_below',
            ],
            'nullable' => [
                3 => true,
                true,
                true,
                true,
                true,
                9 => false,
                11 => false,
            ],
            'precision' => [
                6 => 18,
                18,
            ],
            'scale' => [
                6 => 6,
                6,
            ],
            'fetch' => [
                8 => 2,
                10 => 2,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\WatchlistItem',
                10 => 'App\\Entity\\WatchlistItem',
            ],
            'inversedBy' => [
                8 => 'items',
                10 => 'watchlistItems',
            ],
            'sourceToTargetKeyColumns' => [
                8 => [
                    'watchlist_id' => 'id',
                ],
                10 => [
                    'stock_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                8 => [
                    'id' => 'watchlist_id',
                ],
                10 => [
                    'id' => 'stock_id',
                ],
            ],
            'joinColumns' => [
                8 => [
                    $o[9],
                ],
                10 => [
                    $o[11],
                ],
            ],
            'joinColumnFieldNames' => [
                8 => [
                    'watchlist_id' => 'watchlist_id',
                ],
                10 => [
                    'stock_id' => 'stock_id',
                ],
            ],
            'deferrable' => [
                9 => false,
                11 => false,
            ],
            'unique' => [
                9 => false,
                11 => false,
            ],
            'onDelete' => [
                9 => 'CASCADE',
                11 => 'CASCADE',
            ],
            'referencedColumnName' => [
                9 => 'id',
                11 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'watchlist',
                10 => 'stock',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\Watchlist',
                10 => 'App\\Entity\\Stock',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
