<?php

namespace ContainerVPdxv0r;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountControllerchangePasswordService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.R21nC86.App\Controller\AccountController::changePassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R21nC86.App\\Controller\\AccountController::changePassword()'] = ($container->privates['.service_locator.R21nC86'] ?? $container->load('get_ServiceLocator_R21nC86Service'))->withContext('App\\Controller\\AccountController::changePassword()', $container);
    }
}
