<?php

namespace ContainerVPdxv0r;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Openapi_ProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'api_platform.openapi.provider' shared service.
     *
     * @return \ApiPlatform\OpenApi\State\OpenApiProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'] ?? $container->load('getLoginRequestExampleOpenApiFactoryService'));

        if (isset($container->privates['api_platform.openapi.provider'])) {
            return $container->privates['api_platform.openapi.provider'];
        }

        $instance = new \ApiPlatform\OpenApi\State\OpenApiProvider($a);

        if (isset($container->privates['api_platform.openapi.provider'])) {
            return $container->privates['api_platform.openapi.provider'];
        }

        return $container->privates['api_platform.openapi.provider'] = $instance;
    }
}
