<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260119120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user, watchlist, watchlist_item, stock, password_reset_token tables for the new model';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            first_name VARCHAR(120) DEFAULT NULL,
            last_name VARCHAR(120) DEFAULT NULL,
            email VARCHAR(180) NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');

        $this->addSql('CREATE TABLE stock (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            symbol VARCHAR(32) NOT NULL,
            exchange_code VARCHAR(16) DEFAULT NULL,
            mic VARCHAR(16) DEFAULT NULL,
            isin VARCHAR(32) DEFAULT NULL,
            name VARCHAR(255) DEFAULT NULL,
            type VARCHAR(64) DEFAULT NULL,
            currency VARCHAR(8) DEFAULT NULL,
            country VARCHAR(64) DEFAULT NULL,
            sector VARCHAR(128) DEFAULT NULL,
            industry VARCHAR(128) DEFAULT NULL,
            website VARCHAR(255) DEFAULT NULL,
            description TEXT DEFAULT NULL,
            logo_url VARCHAR(512) DEFAULT NULL,
            last_price DOUBLE PRECISION DEFAULT NULL,
            open DOUBLE PRECISION DEFAULT NULL,
            high DOUBLE PRECISION DEFAULT NULL,
            low DOUBLE PRECISION DEFAULT NULL,
            prev_close DOUBLE PRECISION DEFAULT NULL,
            change DOUBLE PRECISION DEFAULT NULL,
            change_percent DOUBLE PRECISION DEFAULT NULL,
            avg_volume30d DOUBLE PRECISION DEFAULT NULL,
            market_cap DOUBLE PRECISION DEFAULT NULL,
            shares_outstanding DOUBLE PRECISION DEFAULT NULL,
            float_shares DOUBLE PRECISION DEFAULT NULL,
            quote_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            last_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            beta DOUBLE PRECISION DEFAULT NULL,
            dividend_yield DOUBLE PRECISION DEFAULT NULL,
            dividend_rate DOUBLE PRECISION DEFAULT NULL,
            pe_ttm DOUBLE PRECISION DEFAULT NULL,
            pb DOUBLE PRECISION DEFAULT NULL,
            ps_ttm DOUBLE PRECISION DEFAULT NULL,
            ev_ebitda DOUBLE PRECISION DEFAULT NULL,
            week52_high DOUBLE PRECISION DEFAULT NULL,
            week52_low DOUBLE PRECISION DEFAULT NULL,
            active BOOLEAN NOT NULL DEFAULT true,
            data_source VARCHAR(64) DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_stock_symbol ON stock (symbol)');
        $this->addSql('CREATE INDEX idx_stock_exchange_code ON stock (exchange_code)');

        $this->addSql('CREATE TABLE watchlist (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            name VARCHAR(160) NOT NULL,
            description TEXT DEFAULT NULL,
            is_default BOOLEAN NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_watchlist_user_id ON watchlist (user_id)');
        $this->addSql('ALTER TABLE watchlist ADD CONSTRAINT fk_watchlist_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');

        $this->addSql('CREATE TABLE watchlist_item (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            watchlist_id INT NOT NULL,
            stock_id INT NOT NULL,
            added_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            position INT DEFAULT NULL,
            note TEXT DEFAULT NULL,
            tags JSON DEFAULT NULL,
            alert_price_above NUMERIC(18, 6) DEFAULT NULL,
            alert_price_below NUMERIC(18, 6) DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_watchlist_item_watchlist_id ON watchlist_item (watchlist_id)');
        $this->addSql('CREATE INDEX idx_watchlist_item_stock_id ON watchlist_item (stock_id)');
        $this->addSql('ALTER TABLE watchlist_item ADD CONSTRAINT fk_watchlist_item_watchlist FOREIGN KEY (watchlist_id) REFERENCES watchlist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE watchlist_item ADD CONSTRAINT fk_watchlist_item_stock FOREIGN KEY (stock_id) REFERENCES stock (id) ON DELETE CASCADE');

        $this->addSql('CREATE TABLE password_reset_token (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            token_hash VARCHAR(255) NOT NULL,
            expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            ip_address VARCHAR(64) DEFAULT NULL,
            user_agent VARCHAR(255) DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_password_reset_token_user_id ON password_reset_token (user_id)');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT fk_password_reset_token_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('DROP TABLE watchlist_item');
        $this->addSql('DROP TABLE watchlist');
        $this->addSql('DROP TABLE stock');
        $this->addSql('DROP TABLE "user"');
    }
}
