<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVPdxv0r\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVPdxv0r/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVPdxv0r.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVPdxv0r\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVPdxv0r\App_KernelProdContainer([
    'container.build_hash' => 'VPdxv0r',
    'container.build_id' => '713aa4ef',
    'container.build_time' => 1768926382,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVPdxv0r');
