<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM3xozdb\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM3xozdb/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerM3xozdb.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerM3xozdb\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerM3xozdb\App_KernelProdContainer([
    'container.build_hash' => 'M3xozdb',
    'container.build_id' => 'bdcf5dd6',
    'container.build_time' => 1769080686,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM3xozdb');
