<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Stock extends \App\Entity\Stock implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null, 16],
        "\0".parent::class."\0".'avgVolume30d' => [parent::class, 'avgVolume30d', null, 16],
        "\0".parent::class."\0".'beta' => [parent::class, 'beta', null, 16],
        "\0".parent::class."\0".'change' => [parent::class, 'change', null, 16],
        "\0".parent::class."\0".'changePercent' => [parent::class, 'changePercent', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'dataSource' => [parent::class, 'dataSource', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'dividendRate' => [parent::class, 'dividendRate', null, 16],
        "\0".parent::class."\0".'dividendYield' => [parent::class, 'dividendYield', null, 16],
        "\0".parent::class."\0".'evEbitda' => [parent::class, 'evEbitda', null, 16],
        "\0".parent::class."\0".'exchangeCode' => [parent::class, 'exchangeCode', null, 16],
        "\0".parent::class."\0".'floatShares' => [parent::class, 'floatShares', null, 16],
        "\0".parent::class."\0".'high' => [parent::class, 'high', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'industry' => [parent::class, 'industry', null, 16],
        "\0".parent::class."\0".'isin' => [parent::class, 'isin', null, 16],
        "\0".parent::class."\0".'lastPrice' => [parent::class, 'lastPrice', null, 16],
        "\0".parent::class."\0".'lastUpdatedAt' => [parent::class, 'lastUpdatedAt', null, 16],
        "\0".parent::class."\0".'logoUrl' => [parent::class, 'logoUrl', null, 16],
        "\0".parent::class."\0".'low' => [parent::class, 'low', null, 16],
        "\0".parent::class."\0".'marketCap' => [parent::class, 'marketCap', null, 16],
        "\0".parent::class."\0".'mic' => [parent::class, 'mic', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'open' => [parent::class, 'open', null, 16],
        "\0".parent::class."\0".'pb' => [parent::class, 'pb', null, 16],
        "\0".parent::class."\0".'peTtm' => [parent::class, 'peTtm', null, 16],
        "\0".parent::class."\0".'prevClose' => [parent::class, 'prevClose', null, 16],
        "\0".parent::class."\0".'psTtm' => [parent::class, 'psTtm', null, 16],
        "\0".parent::class."\0".'quoteTimestamp' => [parent::class, 'quoteTimestamp', null, 16],
        "\0".parent::class."\0".'sector' => [parent::class, 'sector', null, 16],
        "\0".parent::class."\0".'sharesOutstanding' => [parent::class, 'sharesOutstanding', null, 16],
        "\0".parent::class."\0".'symbol' => [parent::class, 'symbol', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'watchlistItems' => [parent::class, 'watchlistItems', null, 16],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null, 16],
        "\0".parent::class."\0".'week52High' => [parent::class, 'week52High', null, 16],
        "\0".parent::class."\0".'week52Low' => [parent::class, 'week52Low', null, 16],
        'active' => [parent::class, 'active', null, 16],
        'avgVolume30d' => [parent::class, 'avgVolume30d', null, 16],
        'beta' => [parent::class, 'beta', null, 16],
        'change' => [parent::class, 'change', null, 16],
        'changePercent' => [parent::class, 'changePercent', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'dataSource' => [parent::class, 'dataSource', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'dividendRate' => [parent::class, 'dividendRate', null, 16],
        'dividendYield' => [parent::class, 'dividendYield', null, 16],
        'evEbitda' => [parent::class, 'evEbitda', null, 16],
        'exchangeCode' => [parent::class, 'exchangeCode', null, 16],
        'floatShares' => [parent::class, 'floatShares', null, 16],
        'high' => [parent::class, 'high', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'industry' => [parent::class, 'industry', null, 16],
        'isin' => [parent::class, 'isin', null, 16],
        'lastPrice' => [parent::class, 'lastPrice', null, 16],
        'lastUpdatedAt' => [parent::class, 'lastUpdatedAt', null, 16],
        'logoUrl' => [parent::class, 'logoUrl', null, 16],
        'low' => [parent::class, 'low', null, 16],
        'marketCap' => [parent::class, 'marketCap', null, 16],
        'mic' => [parent::class, 'mic', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'open' => [parent::class, 'open', null, 16],
        'pb' => [parent::class, 'pb', null, 16],
        'peTtm' => [parent::class, 'peTtm', null, 16],
        'prevClose' => [parent::class, 'prevClose', null, 16],
        'psTtm' => [parent::class, 'psTtm', null, 16],
        'quoteTimestamp' => [parent::class, 'quoteTimestamp', null, 16],
        'sector' => [parent::class, 'sector', null, 16],
        'sharesOutstanding' => [parent::class, 'sharesOutstanding', null, 16],
        'symbol' => [parent::class, 'symbol', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'watchlistItems' => [parent::class, 'watchlistItems', null, 16],
        'website' => [parent::class, 'website', null, 16],
        'week52High' => [parent::class, 'week52High', null, 16],
        'week52Low' => [parent::class, 'week52Low', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
