<?php

namespace Container4H8b0fF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_HttpClient_PoolService extends App_KernelProdContainer
{
    /*
     * Gets the public 'cache.http_client.pool' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\FilesystemAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['cache.http_client.pool'] = $instance = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('Mtm73AgkT9', 0, (\dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'share'.\DIRECTORY_SEPARATOR.'prod/pools/app'), ($container->privates['cache.default_marshaller'] ??= new \Symfony\Component\Cache\Marshaller\DefaultMarshaller(NULL, false)));

        $instance->setLogger(($container->privates['logger'] ?? self::getLoggerService($container)));

        return $instance;
    }
}
