<?php

namespace Container4H8b0fF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginRequestExampleOpenApiFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\OpenApi\LoginRequestExampleOpenApiFactory' shared autowired service.
     *
     * @return \App\OpenApi\LoginRequestExampleOpenApiFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $b = ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Property_MetadataFactory_CachedService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $c = ($container->privates['api_platform.json_schema.backward_compatible_schema_factory'] ?? $container->load('getApiPlatform_JsonSchema_BackwardCompatibleSchemaFactoryService'));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $d = ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $e = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $f = ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService'));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }

        $instance = new \App\OpenApi\LoginRequestExampleOpenApiFactory(new \Lexik\Bundle\JWTAuthenticationBundle\OpenApi\OpenApiFactory(new \ApiPlatform\OpenApi\Factory\OpenApiFactory(($container->privates['api_platform.metadata.resource.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_NameCollectionFactory_CachedService($container)), $a, ($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService($container)), $b, $c, ($container->privates['api_platform.filter_locator'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], [])), $container->parameters['api_platform.formats'], ($container->privates['api_platform.openapi.options'] ?? $container->load('getApiPlatform_Openapi_OptionsService')), new \ApiPlatform\State\Pagination\PaginationOptions(true, 'page', false, 'itemsPerPage', false, 'pagination', 30, 30, false, false, 'partial'), $d, $container->parameters['api_platform.error_formats']), '/api/login', 'email', 'password'), $e, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $f);

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }

        return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'] = $instance;
    }
}
