<?php

namespace ContainerCMCXqGm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RIgUHp2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RIgUHp2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RIgUHp2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AccountController::changePassword' => ['privates', '.service_locator.R21nC86.App\\Controller\\AccountController::changePassword()', 'getAccountControllerchangePasswordService', true],
            'App\\Controller\\PasswordResetController::confirmReset' => ['privates', '.service_locator.R21nC86.App\\Controller\\PasswordResetController::confirmReset()', 'getPasswordResetControllerconfirmResetService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.G.x3Jou.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AccountController:changePassword' => ['privates', '.service_locator.R21nC86.App\\Controller\\AccountController::changePassword()', 'getAccountControllerchangePasswordService', true],
            'App\\Controller\\PasswordResetController:confirmReset' => ['privates', '.service_locator.R21nC86.App\\Controller\\PasswordResetController::confirmReset()', 'getPasswordResetControllerconfirmResetService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.G.x3Jou.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AccountController::changePassword' => '?',
            'App\\Controller\\PasswordResetController::confirmReset' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AccountController:changePassword' => '?',
            'App\\Controller\\PasswordResetController:confirmReset' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
        ]);
    }
}
