<?php

namespace ContainerCMCXqGm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinnhubClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\StockImport\FinnhubClient' shared autowired service.
     *
     * @return \App\Service\StockImport\FinnhubClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'ProviderClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'FinnhubClient.php';

        return $container->privates['App\\Service\\StockImport\\FinnhubClient'] = new \App\Service\StockImport\FinnhubClient(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('FINNHUB_API_KEY'));
    }
}
