<?php

namespace ContainerCMCXqGm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginRequestExampleOpenApiFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\OpenApi\LoginRequestExampleOpenApiFactory' shared autowired service.
     *
     * @return \App\OpenApi\LoginRequestExampleOpenApiFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'OpenApiFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OpenApi'.\DIRECTORY_SEPARATOR.'LoginRequestExampleOpenApiFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'jwt-authentication-bundle'.\DIRECTORY_SEPARATOR.'OpenApi'.\DIRECTORY_SEPARATOR.'OpenApiFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Serializer'.\DIRECTORY_SEPARATOR.'NormalizeOperationNameTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'TypeFactoryTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'OpenApiFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'state'.\DIRECTORY_SEPARATOR.'Pagination'.\DIRECTORY_SEPARATOR.'PaginationOptions.php';

        $a = ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $b = ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Property_MetadataFactory_CachedService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $c = ($container->privates['api_platform.json_schema.backward_compatible_schema_factory'] ?? $container->load('getApiPlatform_JsonSchema_BackwardCompatibleSchemaFactoryService'));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $d = ($container->privates['api_platform.filter_locator'] ?? self::getApiPlatform_FilterLocatorService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $e = ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $f = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }
        $g = ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService'));

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }

        $instance = new \App\OpenApi\LoginRequestExampleOpenApiFactory(new \Lexik\Bundle\JWTAuthenticationBundle\OpenApi\OpenApiFactory(new \ApiPlatform\OpenApi\Factory\OpenApiFactory(($container->privates['api_platform.metadata.resource.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_NameCollectionFactory_CachedService($container)), $a, ($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService($container)), $b, $c, $d, $container->parameters['api_platform.formats'], ($container->privates['api_platform.openapi.options'] ?? $container->load('getApiPlatform_Openapi_OptionsService')), new \ApiPlatform\State\Pagination\PaginationOptions(true, 'page', true, 'itemsPerPage', true, 'pagination', 30, 200, false, false, 'partial'), $e, $container->parameters['api_platform.error_formats']), '/api/login', 'email', 'password'), $f, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $g);

        if (isset($container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'])) {
            return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'];
        }

        return $container->privates['App\\OpenApi\\LoginRequestExampleOpenApiFactory'] = $instance;
    }
}
