<?php

namespace ContainerCMCXqGm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G.x3Jou.App\Controller\RegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G.x3Jou.App\\Controller\\RegistrationController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'users' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'jwtManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
        ], [
            'users' => 'App\\Repository\\UserRepository',
            'passwordHasher' => '?',
            'entityManager' => '?',
            'jwtManager' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::register()', $container);
    }
}
