<?php

namespace ContainerCMCXqGm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStocksRefreshCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\StocksRefreshCommand' shared autowired service.
     *
     * @return \App\Command\StocksRefreshCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'StocksRefreshCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'StockImportService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'ProviderRateLimiter.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'StockDataMerger.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'StockUniverse.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'StockRefreshLogger.php';

        $a = ($container->privates['App\\Service\\StockImport\\StockRefreshLogger'] ??= new \App\Service\StockImport\StockRefreshLogger((\dirname(__DIR__, 4).'/var/log/stock_refresh.log')));

        $container->privates['App\\Command\\StocksRefreshCommand'] = $instance = new \App\Command\StocksRefreshCommand(new \App\Service\StockImport\StockImportService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\StockImport\ProviderRateLimiter(['fmp' => ['rpm' => $container->getEnv('int:FMP_RPM'), 'rpd' => $container->getEnv('int:FMP_RPD'), 'maxConcurrent' => $container->getEnv('int:FMP_MAX_CONCURRENT')], 'alphavantage' => ['rpm' => $container->getEnv('int:AV_RPM'), 'rpd' => $container->getEnv('int:AV_RPD'), 'maxConcurrent' => $container->getEnv('int:AV_MAX_CONCURRENT')], 'finnhub' => ['rpm' => $container->getEnv('int:FINNHUB_RPM'), 'rpd' => $container->getEnv('int:FINNHUB_RPD'), 'maxConcurrent' => $container->getEnv('int:FINNHUB_MAX_CONCURRENT')], 'twelvedata' => ['rpm' => $container->getEnv('int:TWELVEDATA_RPM'), 'rpd' => $container->getEnv('int:TWELVEDATA_RPD'), 'maxConcurrent' => $container->getEnv('int:TWELVEDATA_MAX_CONCURRENT')]], $a), new \App\Service\StockImport\StockDataMerger(), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Service\\StockImport\\AlphaVantageClient'] ?? $container->load('getAlphaVantageClientService'));
            yield 1 => ($container->privates['App\\Service\\StockImport\\FinnhubClient'] ?? $container->load('getFinnhubClientService'));
            yield 2 => ($container->privates['App\\Service\\StockImport\\FmpClient'] ?? $container->load('getFmpClientService'));
            yield 3 => ($container->privates['App\\Service\\StockImport\\TwelveDataClient'] ?? $container->load('getTwelveDataClientService'));
        }, 4), ['default' => ['fmp', 'finnhub', 'alphavantage', 'twelvedata'], 'price' => $container->getEnv('csv:MERGE_PRIORITY_PRICE'), 'marketCap' => $container->getEnv('csv:MERGE_PRIORITY_MARKETCAP'), 'peTtm' => $container->getEnv('csv:MERGE_PRIORITY_PE'), 'dividendYield' => $container->getEnv('csv:MERGE_PRIORITY_DIVIDEND_YIELD')], $a), new \App\Service\StockImport\StockUniverse((\dirname(__DIR__, 4).'/var/stock_universe.json')), $container->getEnv('int:REFRESH_LOOP_SLEEP_MS'), $container->getEnv('int:REFRESH_IDLE_SLEEP_MS'), $a);

        $instance->setName('app:stocks:refresh');
        $instance->setDescription('Refresh stock data from external providers');

        return $instance;
    }
}
