<?php

namespace ContainerCMCXqGm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockUniverseBuildCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\StockUniverseBuildCommand' shared autowired service.
     *
     * @return \App\Command\StockUniverseBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'StockUniverseBuildCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'StockUniverseBuilder.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StockImport'.\DIRECTORY_SEPARATOR.'StockRefreshLogger.php';

        $container->privates['App\\Command\\StockUniverseBuildCommand'] = $instance = new \App\Command\StockUniverseBuildCommand(new \App\Service\StockImport\StockUniverseBuilder(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('FMP_API_KEY'), $container->getEnv('TWELVEDATA_API_KEY'), ($container->privates['App\\Service\\StockImport\\StockRefreshLogger'] ??= new \App\Service\StockImport\StockRefreshLogger((\dirname(__DIR__, 4).'/var/log/stock_refresh.log')))), (\dirname(__DIR__, 4).'/var/stock_universe.json'));

        $instance->setName('app:stocks:universe:build');
        $instance->setDescription('Build a stock universe list');

        return $instance;
    }
}
