<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIB9taFz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIB9taFz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIB9taFz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIB9taFz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIB9taFz\App_KernelDevDebugContainer([
    'container.build_hash' => 'IB9taFz',
    'container.build_id' => 'c5783eb8',
    'container.build_time' => 1769014824,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIB9taFz');
