<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App_Entity_Stock' => 0,
'App_Entity_User' => 1,
'Symfony_Component_Security_Core_User_UserInterface' => 2,
'Symfony_Component_Security_Core_User_PasswordAuthenticatedUserInterface' => 3,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Stock',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'symbol' => $o[2],
                    'exchangeCode' => $o[3],
                    'mic' => $o[4],
                    'isin' => $o[5],
                    'name' => $o[6],
                    'type' => $o[7],
                    'currency' => $o[8],
                    'country' => $o[9],
                    'sector' => $o[10],
                    'industry' => $o[11],
                    'website' => $o[12],
                    'description' => $o[13],
                    'logoUrl' => $o[14],
                    'lastPrice' => $o[15],
                    'open' => $o[16],
                    'high' => $o[17],
                    'low' => $o[18],
                    'prevClose' => $o[19],
                    'change' => $o[20],
                    'changePercent' => $o[21],
                    'avgVolume30d' => $o[22],
                    'marketCap' => $o[23],
                    'sharesOutstanding' => $o[24],
                    'floatShares' => $o[25],
                    'quoteTimestamp' => $o[26],
                    'lastUpdatedAt' => $o[27],
                    'beta' => $o[28],
                    'dividendYield' => $o[29],
                    'dividendRate' => $o[30],
                    'peTtm' => $o[31],
                    'pb' => $o[32],
                    'psTtm' => $o[33],
                    'evEbitda' => $o[34],
                    'week52High' => $o[35],
                    'week52Low' => $o[36],
                    'active' => $o[37],
                    'dataSource' => $o[38],
                    'watchlistItems' => $o[39],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'symbol',
                'exchangeCode',
                'mic',
                'isin',
                'name',
                'type',
                'currency',
                'country',
                'sector',
                'industry',
                'website',
                'description',
                'logoUrl',
                'lastPrice',
                'open',
                'high',
                'low',
                'prevClose',
                'change',
                'changePercent',
                'avgVolume30d',
                'marketCap',
                'sharesOutstanding',
                'floatShares',
                'quoteTimestamp',
                'lastUpdatedAt',
                'beta',
                'dividendYield',
                'dividendRate',
                'peTtm',
                'pb',
                'psTtm',
                'evEbitda',
                'week52High',
                'week52Low',
                'active',
                'dataSource',
                'watchlistItems',
            ],
            'groups' => [
                1 => [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
                [
                    'stock:read',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\User',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'firstName' => $o[2],
                    'lastName' => $o[3],
                    'email' => $o[4],
                    'passwordHash' => $o[5],
                    'avatarUrl' => $o[6],
                    'createdAt' => $o[7],
                    'updatedAt' => $o[8],
                    'watchlists' => $o[9],
                    'userIdentifier' => $o[10],
                    'roles' => $o[11],
                    'password' => $o[12],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'firstName',
                'lastName',
                'email',
                'passwordHash',
                'avatarUrl',
                'createdAt',
                'updatedAt',
                'watchlists',
                'userIdentifier',
                'roles',
                'password',
            ],
            'groups' => [
                2 => [
                    'user:read',
                    'user:write',
                ],
                [
                    'user:read',
                    'user:write',
                ],
                [
                    'user:read',
                ],
                6 => [
                    'user:read',
                    'user:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            ],
            'attributesMetadata' => [
                [
                    'roles' => $o[1],
                    'userIdentifier' => $o[2],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'roles',
                'userIdentifier',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface',
            ],
            'attributesMetadata' => [
                [
                    'password' => $o[1],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'password',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
