<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WatchlistItem extends \App\Entity\WatchlistItem implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'addedAt' => [parent::class, 'addedAt', null, 16],
        "\0".parent::class."\0".'alertPriceAbove' => [parent::class, 'alertPriceAbove', null, 16],
        "\0".parent::class."\0".'alertPriceBelow' => [parent::class, 'alertPriceBelow', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null, 16],
        "\0".parent::class."\0".'position' => [parent::class, 'position', null, 16],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null, 16],
        "\0".parent::class."\0".'tags' => [parent::class, 'tags', null, 16],
        "\0".parent::class."\0".'watchlist' => [parent::class, 'watchlist', null, 16],
        'addedAt' => [parent::class, 'addedAt', null, 16],
        'alertPriceAbove' => [parent::class, 'alertPriceAbove', null, 16],
        'alertPriceBelow' => [parent::class, 'alertPriceBelow', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'note' => [parent::class, 'note', null, 16],
        'position' => [parent::class, 'position', null, 16],
        'stock' => [parent::class, 'stock', null, 16],
        'tags' => [parent::class, 'tags', null, 16],
        'watchlist' => [parent::class, 'watchlist', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
